feat: disable poetry groups (not compatible with Python 3.6)
Poetry groups where introduced in Poetry 1.2. The same version that stopped supporting Python 3.6 ([ref](https://python-poetry.org/blog/announcing-poetry-1.2.0/#dropping-support-for-python-27-35-and-36-as-runtimes))
That raises the following error when installing.
```
  RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
```
https://stackoverflow.com/questions/73876790/poetry-configuration-is-invalid-additional-properties-are-not-allowed-group